name: untitled
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
